# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2.2"

services:
  vault:
    image: hashicorp/vault:latest
    cap_add:
    - "IPC_LOCK"
    ports:
    - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "TEST"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_TOKEN: "TEST"
      MYSQL_URL: "vault:vault@tcp(mysql:3306)/"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "vault"
      MYSQL_PASSWORD: "vault"
