# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2.2"

services:
  vault:
    image: vault:latest
    cap_add:
    - "IPC_LOCK"
    ports:
    - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "TEST"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_TOKEN: "TEST"
      MYSQL_URL: "vault:vault@tcp(mysql:3306)/"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "vault"
      MYSQL_PASSWORD: "vault"

  elastic:
    image: elasticsearch:7.6.0
    ports:
    - "9200:9200"
    environment:
      "discovery.type": "single-node"
      "xpack.security.enabled": "true"
      "ELASTIC_PASSWORD": "elastic"

  influxdb:
    image: influxdb:1.7.11-alpine
    ports:
    - "8086:8086"
    environment:
      "DOCKER_INFLUXDB_INIT_USERNAME": "admin"
      "DOCKER_INFLUXDB_INIT_PASSWORD": "password"
      "DOCKER_INFLUXDB_INIT_ORG": "test"
      "DOCKER_INFLUXDB_INIT_BUCKET": "test"

  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=alice,bob
      - LDAP_PASSWORDS=password1,password2

  # openldap_setup will seed the openldap container with ldif data
  openldap_setup:
    image: docker.io/bitnami/openldap:2.6
    depends_on:
      - openldap
    restart: "no"
    entrypoint: [ "bash", "-c", "ldapadd -x -w \"adminpassword\" -D \"cn=admin,dc=example,dc=org\" -f ./testdata/ldap/seed.ldif -v -h openldap:1389 -c"]
